### PR TITLE
fix: type mismatch when parsing JSON

### LINKED ISSUE #217: Markdown tables cause memos to not load
Memos server 0.22.3. 

To reproduce:
- Start with 0.22.3 memos server with handful of memos
- add a memo with a table such as:

```markdown
| **Feature** | **i3** | **i5** | **i7** | **i9** |
| --- | --- | --- | --- | --- |
| **Target Users** | Entry-level consumers | Mainstream users | High-end users | Enthusiasts and professionals |
| **Core Count** | 2-4 cores | 4-6 cores | 6-8 cores | 8-10+ cores |
| **Threads** | 4-8 threads | 8-12 threads | 12-16 threads | 16-20+ threads |
| **Clock Speed** | Lower base and boost speeds | Moderate base and boost speeds | High base and boost speeds | Highest base and boost speeds |
| **Cache Size** | Smaller cache | Moderate cache | Larger cache | Largest cache |
| **TDP** | Lower power consumption | Moderate power consumption | Higher power consumption | Highest power consumption |
| **Use Cases** | Basic computing, web browsing | Office applications, light gaming | Content creation, gaming | High-end gaming, professional work |
```

Memos do not load after this memo is added to the server

### PR DESCRIPTION
**Pull request by mudkipme**
Resolves #217

### CODE REVIEW

**Comment by haripalat** [comment]
Hi @mudkipme, when will change reflect on iOS as a user for me

**Comment by mudkipme** [comment]
> Hi @mudkipme, when will change reflect on iOS as a user for me

A TestFlight version is submitted to Apple and you can download at https://testflight.apple.com/join/YVHheZ50 when it's approved.

**Comment by haripalat** [comment]
Hi @mudkipme  I’ll wait for the actual version to come out. Thanks for the update!

**Comment by haripalat** [comment]
Hi @mudkipme - when will I see it in the actual update for me. Instead of test flight version. What is the typical wait time?

**Comment by mudkipme** [comment]
> Hi @mudkipme - when will I see it in the actual update for me. Instead of test flight version. What is the typical wait time?

Moe Memos 1.7 is submitted to App Store and should be available soon.

**Comment by haripalat** [comment]
Hi @mudkipme  I got the update. It is working now. Thank you!

**Pull request merged**
